/*
 *April 2
 *family planner program that manipulates data and tells a user how theyre doing financially
 *Netbeans' weird formatting causes the bars to resize to the size of the first bar
 */

/**
 *
 * @author eljam3239
 */
public class ad extends javax.swing.JFrame {

    /**
     * Creates new form ad
     */
    public ad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputpanel = new javax.swing.JPanel();
        p1title = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        housinglabel = new javax.swing.JLabel();
        transportlabel = new javax.swing.JLabel();
        lifelabel = new javax.swing.JLabel();
        savinglabel = new javax.swing.JLabel();
        incomelabel = new javax.swing.JLabel();
        housinginput = new javax.swing.JTextField();
        transportinput = new javax.swing.JTextField();
        lifeinput = new javax.swing.JTextField();
        savingsinput = new javax.swing.JTextField();
        incomeinput = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        graphpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        housing2 = new javax.swing.JLabel();
        transport2 = new javax.swing.JLabel();
        life2 = new javax.swing.JLabel();
        savings2 = new javax.swing.JLabel();
        housingbar = new javax.swing.JLabel();
        transportbar = new javax.swing.JLabel();
        lifebar = new javax.swing.JLabel();
        savingsbar = new javax.swing.JLabel();
        housingpercent = new javax.swing.JLabel();
        transportpercent = new javax.swing.JLabel();
        lifepercent = new javax.swing.JLabel();
        savingspercent = new javax.swing.JLabel();
        textpanel = new javax.swing.JPanel();
        housingoutput = new javax.swing.JLabel();
        transportoutput = new javax.swing.JLabel();
        lifeoutput = new javax.swing.JLabel();
        savingsoutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputpanel.setBackground(new java.awt.Color(255, 153, 255));
        inputpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 153)));

        p1title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1title.setText("Family Budget");

        info.setText("Enter the amount you spend in each category per month.");

        housinglabel.setText("Housing");

        transportlabel.setText("Transportation");

        lifelabel.setText("Life");

        savinglabel.setText("Savings");

        incomelabel.setText("Net Income");

        enter.setText("Calculate");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputpanelLayout = new javax.swing.GroupLayout(inputpanel);
        inputpanel.setLayout(inputpanelLayout);
        inputpanelLayout.setHorizontalGroup(
            inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputpanelLayout.createSequentialGroup()
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputpanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1title)))
                    .addGroup(inputpanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transportlabel)
                            .addComponent(housinglabel)
                            .addComponent(lifelabel)
                            .addComponent(savinglabel)
                            .addComponent(incomelabel))
                        .addGap(50, 50, 50)
                        .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(incomeinput, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(savingsinput)
                            .addComponent(lifeinput)
                            .addComponent(transportinput)
                            .addComponent(housinginput)))
                    .addGroup(inputpanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(enter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputpanelLayout.setVerticalGroup(
            inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housinglabel)
                    .addComponent(housinginput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportlabel)
                    .addComponent(transportinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lifelabel)
                    .addComponent(lifeinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingsinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savinglabel))
                .addGap(18, 18, 18)
                .addGroup(inputpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incomelabel)
                    .addComponent(incomeinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enter)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        graphpanel.setBackground(new java.awt.Color(153, 255, 255));
        graphpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 153)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Monthly Spending");

        housing2.setText("Housing:");

        transport2.setText("Transportation:");

        life2.setText("Life:");

        savings2.setText("Savings:");

        housingbar.setBackground(new java.awt.Color(255, 0, 0));
        housingbar.setOpaque(true);

        transportbar.setBackground(new java.awt.Color(255, 255, 51));
        transportbar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transportbar.setOpaque(true);

        lifebar.setBackground(new java.awt.Color(0, 255, 0));
        lifebar.setOpaque(true);

        savingsbar.setBackground(new java.awt.Color(0, 0, 255));
        savingsbar.setOpaque(true);

        housingpercent.setText("   ");

        transportpercent.setText("        ");

        lifepercent.setText("   ");

        savingspercent.setText("    ");

        javax.swing.GroupLayout graphpanelLayout = new javax.swing.GroupLayout(graphpanel);
        graphpanel.setLayout(graphpanelLayout);
        graphpanelLayout.setHorizontalGroup(
            graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graphpanelLayout.createSequentialGroup()
                        .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(graphpanelLayout.createSequentialGroup()
                                    .addComponent(life2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lifepercent))
                                .addGroup(graphpanelLayout.createSequentialGroup()
                                    .addComponent(savings2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(savingspercent)))
                            .addGroup(graphpanelLayout.createSequentialGroup()
                                .addComponent(housing2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(housingpercent)
                                .addGap(3, 3, 3)))
                        .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(graphpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(181, 181, 181))
                            .addGroup(graphpanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(housingbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lifebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(transportbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(savingsbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(graphpanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(transport2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transportpercent)
                        .addContainerGap())))
        );
        graphpanelLayout.setVerticalGroup(
            graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(graphpanelLayout.createSequentialGroup()
                        .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(graphpanelLayout.createSequentialGroup()
                                .addComponent(savingsbar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(transport2)
                                        .addComponent(transportpercent))
                                    .addComponent(transportbar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(life2)
                                .addComponent(lifepercent)))
                        .addGap(18, 18, 18)
                        .addComponent(lifebar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savings2)
                        .addComponent(savingspercent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graphpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(housing2)
                        .addComponent(housingpercent))
                    .addComponent(housingbar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        textpanel.setBackground(new java.awt.Color(153, 255, 153));
        textpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 153)));

        javax.swing.GroupLayout textpanelLayout = new javax.swing.GroupLayout(textpanel);
        textpanel.setLayout(textpanelLayout);
        textpanelLayout.setHorizontalGroup(
            textpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textpanelLayout.createSequentialGroup()
                .addGroup(textpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(textpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(housingoutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transportoutput, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                    .addComponent(lifeoutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savingsoutput, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        textpanelLayout.setVerticalGroup(
            textpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(housingoutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transportoutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeoutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savingsoutput)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        double housing, transport, life, savings, netincome;
        double housingpercent1, transportpercent1, lifepercent1, savingspercent1;
        
        housing = Double.parseDouble(housinginput.getText());
        transport = Double.parseDouble(transportinput.getText());
        life = Double.parseDouble(lifeinput.getText());
        savings = Double.parseDouble(savingsinput.getText());
        netincome = Double.parseDouble(incomeinput.getText());
        
        housingpercent1 = housing/netincome*100;
        transportpercent1 = transport/netincome*100;
        lifepercent1 = life/netincome*100;
        savingspercent1 = savings/netincome*100;
        
        int housingpercentage=(int)housingpercent1;
        int transportpercentage=(int)transportpercent1;
        int lifepercentage=(int)lifepercent1;
        int savingspercentage=(int)savingspercent1;
        
        housingpercent.setText(Double.toString(housingpercentage));
        transportpercent.setText(Double.toString(transportpercentage));
        lifepercent.setText(Double.toString(lifepercentage));
        savingspercent.setText(Double.toString(savingspercentage));
        
        String housespace="", transportspace="", lifespace="", savingspace="";
        
        for (int i = 1; i<=housingpercentage;i++){//creates bars and formats them to the labels
            housespace+=" ";
        }housingbar.setText(housespace);
        for (int i = 0;i<=transportpercentage;i++){
            transportspace+=" ";
        }transportbar.setText(transportspace);
        for (int i=0;i<=lifepercentage;i++){
            lifespace+=" ";
        }lifebar.setText(lifespace);
        for (int i = 0;i<=savingspercentage; i++){
            savingspace+=" ";
            System.out.println(i);
        }savingsbar.setText(savingspace);
        
        if (housingpercentage>35){//outputs weither or not the user's input is good or bad based on economic standards
            housingoutput.setText("You're spending too much money on housing! Pay no more than 35% of your income towards housing");
        } else if (housingpercentage<36){
            housingoutput.setText("You're spending the right amount on housing!");
        } 
        if (transportpercentage>15){
            transportoutput.setText("You spend too much on transport! Spend no more than 15% of your income on transportation!");
        } else if(transportpercentage<=15){
            transportoutput.setText("You're spending the right amount on transportation!");
        } 
        if (lifepercentage>25){
            lifeoutput.setText("You're spending too much on \"life\". Spend no more than 25% of your income on life!");
        } else if (lifepercentage<=25){
            lifeoutput.setText("You're spending the right amount on life.");
        } 
        if (savingspercentage<10){
            savingsoutput.setText("You need to invest more in your future. Put at least 10% of your income towards savings.");
        }else if (savingspercentage>10){
            savingsoutput.setText("Good job! You're investing enough in your savings.");
        }
        
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JPanel graphpanel;
    private javax.swing.JLabel housing2;
    private javax.swing.JLabel housingbar;
    private javax.swing.JTextField housinginput;
    private javax.swing.JLabel housinglabel;
    private javax.swing.JLabel housingoutput;
    private javax.swing.JLabel housingpercent;
    private javax.swing.JTextField incomeinput;
    private javax.swing.JLabel incomelabel;
    private javax.swing.JLabel info;
    private javax.swing.JPanel inputpanel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel life2;
    private javax.swing.JLabel lifebar;
    private javax.swing.JTextField lifeinput;
    private javax.swing.JLabel lifelabel;
    private javax.swing.JLabel lifeoutput;
    private javax.swing.JLabel lifepercent;
    private javax.swing.JLabel p1title;
    private javax.swing.JLabel savinglabel;
    private javax.swing.JLabel savings2;
    private javax.swing.JLabel savingsbar;
    private javax.swing.JTextField savingsinput;
    private javax.swing.JLabel savingsoutput;
    private javax.swing.JLabel savingspercent;
    private javax.swing.JPanel textpanel;
    private javax.swing.JLabel transport2;
    private javax.swing.JLabel transportbar;
    private javax.swing.JTextField transportinput;
    private javax.swing.JLabel transportlabel;
    private javax.swing.JLabel transportoutput;
    private javax.swing.JLabel transportpercent;
    // End of variables declaration//GEN-END:variables
}
